language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn add coverage
  - yarn run test -- -u --coverage 

after_success:
 - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls